print("first line of code")
print("second line of code")
print("                  third line of code")
print(123)

print("        ^")
print("       ^^^")
print("      ^^^^^")
print("     ^^^^^^^")
print("    ^^^^^^^^^")
print("       ^^^")
print("       ^^^")
